// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

type Service struct {
	ID                 string      `json:"id"`
	ServiceName        string      `json:"service_name"`
	StartupTime        interface{} `json:"startup_time"`
	Status             string      `json:"status"`
	Command            string      `json:"command"`
	HealtcheckEndpoint string      `json:"healtcheck_endpoint"`
	PingTime           string      `json:"ping_time"`
	Pid                int64       `json:"pid"`
}
