// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	ServiceChangeStatus(ctx context.Context, arg ServiceChangeStatusParams) error
	ServiceCreate(ctx context.Context, arg ServiceCreateParams) error
	ServiceDeleteByName(ctx context.Context, serviceName string) error
	ServiceFullUpdate(ctx context.Context, arg ServiceFullUpdateParams) error
	ServiceGetAll(ctx context.Context) ([]Service, error)
	ServiceGetByName(ctx context.Context, serviceName string) (Service, error)
	ServiceUpdateStatus(ctx context.Context, arg ServiceUpdateStatusParams) error
}

var _ Querier = (*Queries)(nil)
