// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: services.sql

package db

import (
	"context"
)

const serviceChangeStatus = `-- name: ServiceChangeStatus :exec
UPDATE services SET "status" = ? WHERE "service_name" = ?
`

type ServiceChangeStatusParams struct {
	Status      string `json:"status"`
	ServiceName string `json:"service_name"`
}

func (q *Queries) ServiceChangeStatus(ctx context.Context, arg ServiceChangeStatusParams) error {
	_, err := q.db.ExecContext(ctx, serviceChangeStatus, arg.Status, arg.ServiceName)
	return err
}

const serviceCreate = `-- name: ServiceCreate :exec
INSERT INTO "services" ("id","service_name","startup_time","status","command","healtcheck_endpoint","ping_time","pid")
    VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type ServiceCreateParams struct {
	ID                 string      `json:"id"`
	ServiceName        string      `json:"service_name"`
	StartupTime        interface{} `json:"startup_time"`
	Status             string      `json:"status"`
	Command            string      `json:"command"`
	HealtcheckEndpoint string      `json:"healtcheck_endpoint"`
	PingTime           string      `json:"ping_time"`
	Pid                int64       `json:"pid"`
}

func (q *Queries) ServiceCreate(ctx context.Context, arg ServiceCreateParams) error {
	_, err := q.db.ExecContext(ctx, serviceCreate,
		arg.ID,
		arg.ServiceName,
		arg.StartupTime,
		arg.Status,
		arg.Command,
		arg.HealtcheckEndpoint,
		arg.PingTime,
		arg.Pid,
	)
	return err
}

const serviceDeleteByName = `-- name: ServiceDeleteByName :exec
DELETE FROM "services" WHERE "service_name" = ?
`

func (q *Queries) ServiceDeleteByName(ctx context.Context, serviceName string) error {
	_, err := q.db.ExecContext(ctx, serviceDeleteByName, serviceName)
	return err
}

const serviceFullUpdate = `-- name: ServiceFullUpdate :exec
UPDATE services SET 
    "service_name" = ?,
    "status" = ?,
    "command" = ?,
    "healtcheck_endpoint" = ?,
    "ping_time" = ?
WHERE "service_name" = ?
`

type ServiceFullUpdateParams struct {
	ServiceName        string `json:"service_name"`
	Status             string `json:"status"`
	Command            string `json:"command"`
	HealtcheckEndpoint string `json:"healtcheck_endpoint"`
	PingTime           string `json:"ping_time"`
	ServiceName_2      string `json:"service_name_2"`
}

func (q *Queries) ServiceFullUpdate(ctx context.Context, arg ServiceFullUpdateParams) error {
	_, err := q.db.ExecContext(ctx, serviceFullUpdate,
		arg.ServiceName,
		arg.Status,
		arg.Command,
		arg.HealtcheckEndpoint,
		arg.PingTime,
		arg.ServiceName_2,
	)
	return err
}

const serviceGetAll = `-- name: ServiceGetAll :many
SELECT id, service_name, startup_time, status, command, healtcheck_endpoint, ping_time, pid FROM "services"
`

func (q *Queries) ServiceGetAll(ctx context.Context) ([]Service, error) {
	rows, err := q.db.QueryContext(ctx, serviceGetAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Service{}
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.ServiceName,
			&i.StartupTime,
			&i.Status,
			&i.Command,
			&i.HealtcheckEndpoint,
			&i.PingTime,
			&i.Pid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const serviceGetByName = `-- name: ServiceGetByName :one
SELECT id, service_name, startup_time, status, command, healtcheck_endpoint, ping_time, pid FROM "services" WHERE "service_name" = ?
`

func (q *Queries) ServiceGetByName(ctx context.Context, serviceName string) (Service, error) {
	row := q.db.QueryRowContext(ctx, serviceGetByName, serviceName)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.ServiceName,
		&i.StartupTime,
		&i.Status,
		&i.Command,
		&i.HealtcheckEndpoint,
		&i.PingTime,
		&i.Pid,
	)
	return i, err
}
